export const SelectedList = [
    {
        img: '',
        type: '일반',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '일반',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '일반',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        상점이름: '레아꽃집',
    },
    {
        img: '',
        type: '일반',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: false,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '일반',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: false,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: false,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: false,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: false,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
    {
        img: '',
        type: '클래스',
        name: '꽃다발',
        location: '강남',
        price: '30000',
        discount: '15000',
        당일예약가능여부: true,
        store: '레아꽃집',
    },
];
