export const ReservationData = [
    {
        product: '사랑스러운 꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request:
            '예쁘게 만들어주세요~~~~~~ 최대한 예쁘게 예쁘게 예쁘게 핑크빛 위주로 만들어주세요.예쁘게 만들어주세요~~~~~~ ',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '퀵',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
    {
        product: '꽃다발',
        name: '레아',
        howToFind: '픽업',
        time: '2024/04/27 PM 2:00',
        count: 1,
        price: '50,000원',
        complete: 'yes',
        request: '',
    },
];
